# Site settings
title: Ion
email: claire.antel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Let the sandwiches be known! This is documentation of sandwiches eaten on (but not exlcusive to)
  our alpine adventures. It is all about the who, the what, and the wich!
baseurl: "/the-sandwich-blog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: cmoo_antel
github_username:  cantel

# Build settings
markdown: kramdown
